(ns website.zones.data
  (:require [hickory.core :as h]
            [hickory.select :as sel]
            [clj-http.client :as client]))

(def root "https://www.zeitverschiebung.net/en/all-time-zones.html")

(defn parse [url]
  (-> (client/get url) :body h/parse h/as-hickory))

(defn rows-with-offset
  "NEEDS WORK"
  [offset-regex hdoc]
  (sel/select (sel/and (sel/tag :tr)
                       (sel/has-descendant
                        (sel/find-in-text (re-pattern
                                           (str "^UTC" offset-regex "$")))))
              hdoc))

(defn cities-in-row [hrow]
  (let [city-anchors (sel/select
                      (sel/child (sel/and (sel/tag :td)
                                          sel/last-child)
                                 (sel/tag :a))
                      hrow)]
    (map #(-> % :content last) city-anchors)))

(defn cities-with-offset
  "Returns all cities with the given `offset-str` in the hickory doc `hdoc`"
  [offset-regex hdoc]
  (let [rows (rows-with-offset offset-regex hdoc)]
    (reduce concat
            (map cities-in-row rows))))

(defn offset-map [all-offsets hdoc]
  (loop [res       {}
         remaining all-offsets]
    (if (empty? remaining)
      res
      (let [offset       (first remaining)
            offset-regex (str (if (<= 0 offset) "\\+" "") offset)]
        (recur (assoc res
                      offset
                      (cities-with-offset offset-regex hdoc))
               (rest remaining))))))

(def scraped {0
              '("Abidjan"
                "Abobo"
               "Bouaké"
               "Daloa"
               "San-Pédro"
               "Accra"
               "Kumasi"
               "Tamale"
               "Takoradi"
               "Atsiaman"
               "Bamako"
               "Sikasso"
               "Mopti"
               "Koutiala"
               "Ségou"
               "Serekunda"
               "Brikama"
               "Bakau"
               "Banjul"
               "Farafenni"
               "Bissau"
               "Bafatá"
               "Gabú"
               "Bissorã"
               "Bolama"
               "Camayenne"
               "Conakry"
               "Nzérékoré"
               "Kindia"
               "Kankan"
               "Dakar"
               "Pikine"
               "Touba"
               "Thiès"
               "Thiès Nones"
               "Freetown"
               "Bo"
               "Kenema"
               "Koidu"
               "Makeni"
               "Lomé"
               "Sokodé"
               "Kara"
               "Atakpamé"
               "Kpalimé"
               "Monrovia"
               "Gbarnga"
               "Kakata"
               "Bensonville"
               "Harper"
               "Nouakchott"
               "Nouadhibou"
               "Néma"
               "Kaédi"
               "Rosso"
               "Ouagadougou"
               "Bobo-Dioulasso"
               "Koudougou"
               "Ouahigouya"
               "Banfora"
               "São Tomé"
               "Santo António"
               "Las Palmas de Gran Canaria"
               "Santa Cruz de Tenerife"
               "La Laguna"
               "Telde"
               "Arona"
               "Tórshavn"
               "Klaksvík"
               "Fuglafjørður"
               "Tvøroyri"
               "Miðvágur"
               "Funchal"
               "Câmara de Lobos"
               "São Martinho"
               "Caniço"
               "Machico"
               "Reykjavík"
               "Kópavogur"
               "Hafnarfjörður"
               "Akureyri"
               "Garðabær"
               "Jamestown"
               "Georgetown"
               "Edinburgh of the Seven Seas"
               "Saint Peter Port"
               "Torteval"
               "Saint Sampson"
               "St Anne"
               "Saint Saviour"
               "Douglas"
               "Ramsey"
               "Peel"
               "Port Erin"
               "Castletown"
               "Saint Helier"
               "Le Hocq"
               "Lisbon"
               "Porto"
               "Amadora"
               "Braga"
               "Setúbal"
               "London"
               "Birmingham"
               "Liverpool"
               "Nottingham"
               "Sheffield"),
              -12 (),
              -4
              '("The Valley"
               "Blowing Point Village"
               "Sandy Ground Village"
               "West End Village"
               "East End Village"
               "Saint John’s"
               "Piggotts"
               "Bolands"
               "Codrington"
               "Parham"
               "Oranjestad"
               "Tanki Leendert"
               "San Nicolas"
               "Santa Cruz"
               "Paradera"
               "Asunción"
               "Ciudad del Este"
               "San Lorenzo"
               "Capiatá"
               "Lambaré"
               "Bridgetown"
               "Speightstown"
               "Oistins"
               "Bathsheba"
               "Holetown"
               "Lévis"
               "Boa Vista"
               "Campo Grande"
               "Dourados"
               "Corumbá"
               "Três Lagoas"
               "Ponta Porã"
               "Caracas"
               "Maracaibo"
               "Maracay"
               "Valencia"
               "Barquisimeto"
               "Cuiabá"
               "Várzea Grande"
               "Rondonópolis"
               "Sinop"
               "Barra do Garças"
               "Willemstad"
               "Sint Michiel Liber"
               "Roseau"
               "Portsmouth"
               "Berekua"
               "Saint Joseph"
               "Wesley"
               "Sydney"
               "Glace Bay"
               "Sydney Mines"
               "Labrador City"
               "Happy Valley-Goose Bay"
               "Saint George's"
               "Gouyave"
               "Grenville"
               "Victoria"
               "Saint David’s"
               "Les Abymes"
               "Baie-Mahault"
               "Le Gosier"
               "Petit-Bourg"
               "Sainte-Anne"
               "Georgetown"
               "Linden"
               "New Amsterdam"
               "Anna Regina"
               "Bartica"
               "Halifax"
               "Dartmouth"
               "Charlottetown"
               "Lower Sackville"
               "Truro"
               "Kralendijk"
               "Oranjestad"
               "The Bottom"
               "Santa Cruz de la Sierra"
               "Cochabamba"
               "La Paz"
               "Sucre"
               "Oruro"
               "Cul de Sac"
               "Lower Prince’s Quarter"
               "Koolbaai"
               "Philipsburg"
               "Manaus"
               "Itacoatiara"
               "Parintins"
               "Manacapuru"
               "Coari"
               "Marigot"
               "Fort-de-France"
               "Le Lamentin"
               "Le Robert"
               "Sainte-Marie"
               "Le François"
               "Moncton"
               "Saint John"
               "Fredericton"
               "Dieppe"
               "Miramichi"
               "Brades"
               "Saint Peters"
               "Plymouth"
               "Porto Velho"
               "Ji Paraná"
               "Vilhena"
               "Ariquemes"
               "Cacoal"
               "Chaguanas"
               "Mon Repos"
               "San Fernando"
               "Port of Spain"
               "Rio Claro"
               "San Juan"
               "Bayamón"
               "Carolina"
               "Ponce"
               "Caguas"
               "Santiago"
               "Puente Alto"
               "Antofagasta"
               "Viña del Mar"
               "Valparaíso"
               "Santo Domingo"
               "Santiago de los Caballeros"
               "Santo Domingo Oeste"
               "Santo Domingo Este"
               "San Pedro de Macorís"
               "Gustavia"
               "Basseterre"
               "Fig Tree"
               "Market Shop"
               "Saint Paul’s"
               "Middle Island"
               "Castries"
               "Bisee"
               "Vieux Fort"
               "Micoud"
               "Soufrière"
               "Saint Croix"
               "Charlotte Amalie"
               "Cruz Bay"
               "Kingstown"
               "Kingstown Park"
               "Georgetown"
               "Barrouallie"
               "Port Elizabeth"
               "Road Town"
               "Hamilton"),
              7
              '("Bangkok"
               "Samut Prakan"
               "Mueang Nonthaburi"
               "Udon Thani"
               "Chon Buri"
               "Barnaul"
               "Biysk"
               "Rubtsovsk"
               "Novoaltaysk"
               "Gorno-Altaysk"
               "Khovd"
               "Ölgii"
               "Ulaangom"
               "Uliastay"
               "Altai"
               "Ho Chi Minh City"
               "Hanoi"
               "Da Nang"
               "Haiphong"
               "Biên Hòa"
               "Jakarta"
               "Surabaya"
               "Medan"
               "Bandung"
               "Bekasi"
               "Krasnoyarsk"
               "Abakan"
               "Norilsk"
               "Achinsk"
               "Kyzyl"
               "Novokuznetsk"
               "Kemerovo"
               "Prokop’yevsk"
               "Leninsk-Kuznetsky"
               "Kiselëvsk"
               "Novosibirsk"
               "Berdsk"
               "Iskitim"
               "Akademgorodok"
               "Kuybyshev"
               "Phnom Penh"
               "Takeo"
               "Sihanoukville"
               "Battambang"
               "Siem Reap"
               "Pontianak"
               "Tanjung Pinang"
               "Palangkaraya"
               "Singkawang"
               "Sampit"
               "Tomsk"
               "Seversk"
               "Strezhevoy"
               "Kolpashevo"
               "Asino"
               "Vientiane"
               "Pakse"
               "Thakhèk"
               "Savannakhet"
               "Luang Prabang"
               "Flying Fish Cove"),
              1
              '("Algiers"
               "Boumerdas"
               "Oran"
               "Tébessa"
               "Constantine"
               "Bangui"
               "Bimbo"
               "Mbaïki"
               "Berbérati"
               "Kaga Bandoro"
               "Brazzaville"
               "Pointe-Noire"
               "Dolisie"
               "Kayes"
               "Owando"
               "Casablanca"
               "Rabat"
               "Fès"
               "Sale"
               "Marrakesh"
               "Ceuta"
               "Melilla"
               "Douala"
               "Yaoundé"
               "Garoua"
               "Kousséri"
               "Bamenda"
               "Laayoune"
               "Dakhla"
               "Laayoune Plage"
               "Kinshasa"
               "Masina"
               "Kikwit"
               "Mbandaka"
               "Matadi"
               "Lagos"
               "Kano"
               "Ibadan"
               "Kaduna"
               "Port Harcourt"
               "Libreville"
               "Port-Gentil"
               "Franceville"
               "Oyem"
               "Moanda"
               "Luanda"
               "N’dalatando"
               "Huambo"
               "Lobito"
               "Benguela"
               "Bata"
               "Malabo"
               "Ebebiyin"
               "Aconibe"
               "Añisoc"
               "N'Djamena"
               "Moundou"
               "Sarh"
               "Abéché"
               "Kelo"
               "Niamey"
               "Zinder"
               "Maradi"
               "Agadez"
               "Alaghsas"
               "Cotonou"
               "Abomey-Calavi"
               "Djougou"
               "Porto-Novo"
               "Parakou"
               "Tunis"
               "Sfax"
               "Sousse"
               "Kairouan"
               "Bizerte"
               "Longyearbyen"
               "Olonkinbyen"
               "Amsterdam"
               "Rotterdam"
               "The Hague"
               "Utrecht"
               "Eindhoven"
               "Andorra la Vella"
               "les Escaldes"
               "Encamp"
               "Sant Julià de Lòria"
               "la Massana"
               "Belgrade"
               "Pristina"
               "Niš"
               "Novi Sad"
               "Prizren"
               "Berlin"
               "Hamburg"
               "Munich"
               "Köln"
               "Frankfurt am Main"
               "Bratislava"
               "Košice"
               "Prešov"
               "Nitra"
               "Žilina"
               "Brussels"
               "Antwerpen"
               "Gent"
               "Charleroi"
               "Liège"
               "Budapest"
               "Debrecen"
               "Miskolc"
               "Szeged"
               "Pécs"
               "Copenhagen"
               "Århus"
               "Odense"
               "Aalborg"
               "Frederiksberg"
               "Dublin"
               "Cork"
               "Luimneach"
               "Gaillimh"
               "Tallaght"
               "Gibraltar"
               "Ljubljana"
               "Maribor"
               "Celje"
               "Kranj"
               "Velenje"
               "Luxembourg"
               "Esch-sur-Alzette"
               "Dudelange"
               "Schifflange"
               "Bettembourg"
               "Madrid"
               "Barcelona"
               "Valencia"
               "Sevilla"
               "Zaragoza"
               "Birkirkara"
               "Qormi"
               "Mosta"
               "Żabbar"
               "San Pawl il-Baħar"
               "Monaco"
               "Monte-Carlo"
               "La Condamine"
               "Oslo"
               "Bergen"
               "Trondheim"
               "Stavanger"
               "Drammen"
               "Paris"
               "Marseille"
               "Lyon"
               "Toulouse"
               "Nice"
               "Podgorica"
               "Nikšić"
               "Herceg Novi"
               "Pljevlja"
               "Budva"
               "Prague"
               "Brno"
               "Ostrava"
               "Pilsen"
               "Olomouc"
               "Rome"
               "Milan"
               "Naples"
               "Turin"
               "Palermo"
               "Serravalle"
               "Borgo Maggiore"
               "San Marino"
               "Domagnano"
               "Fiorentino"
               "Sarajevo"
               "Banja Luka"
               "Zenica"
               "Tuzla"
               "Mostar"
               "Skopje"
               "Bitola"
               "Kumanovo"
               "Prilep"
               "Tetovo"
               "Stockholm"
               "Göteborg"
               "Malmö"
               "Uppsala"
               "Sollentuna"
               "Tirana"
               "Durrës"
               "Elbasan"
               "Vlorë"
               "Shkodër"
               "Schaan"
               "Vaduz"
               "Triesen"
               "Balzers"
               "Eschen"
               "Vatican City"
               "Vienna"
               "Graz"
               "Linz"
               "Favoriten"
               "Donaustadt"
               "Warsaw"
               "Łódź"
               "Kraków"
               "Wrocław"
               "Poznań"
               "Zagreb"
               "Split"
               "Rijeka"
               "Osijek"
               "Zadar"
               "Zürich"
               "Genève"
               "Basel"
               "Bern"
               "Lausanne"),
              -2 '("Itamaracá" "Grytviken"),
              4
              '("Baku"
               "Ganja"
               "Sumqayıt"
               "Lankaran"
               "Yevlakh"
               "Dubai"
               "Sharjah"
               "Abu Dhabi"
               "Ajman City"
               "Ras Al Khaimah City"
               "Muscat"
               "Seeb"
               "Şalālah"
               "Bawshar"
               "Sohar"
               "Tbilisi"
               "Kutaisi"
               "Batumi"
               "Sokhumi"
               "Zugdidi"
               "Yerevan"
               "Gyumri"
               "Vanadzor"
               "Vagharshapat"
               "Hrazdan"
               "Astrakhan"
               "Akhtubinsk"
               "Znamensk"
               "Kharabali"
               "Kamyzyak"
               "Samara"
               "Tol’yatti"
               "Izhevsk"
               "Syzran’"
               "Novokuybyshevsk"
               "Saratov"
               "Balakovo"
               "Engel’s"
               "Balashov"
               "Vol’sk"
               "Ulyanovsk"
               "Dimitrovgrad"
               "Inza"
               "Barysh"
               "Novoul’yanovsk"
               "Volgograd"
               "Volzhskiy"
               "Kamyshin"
               "Mikhaylovka"
               "Uryupinsk"
               "Victoria"
               "Anse Boileau"
               "Bel Ombre"
               "Beau Vallon"
               "Cascade"
               "Port Louis"
               "Beau Bassin-Rose Hill"
               "Vacoas"
               "Curepipe"
               "Quatre Bornes"
               "Saint-Denis"
               "Saint-Paul"
               "Saint-Pierre"
               "Le Tampon"
               "Saint-André"),
              -1
              '("Ponta Delgada"
               "Lagoa"
               "Angra do Heroísmo"
               "Rosto de Cão"
               "Rabo de Peixe"
               "Praia"
               "Mindelo"
               "Santa Maria"
               "Cova Figueira"
               "Santa Cruz"),
              -8
              '("Los Angeles"
               "San Diego"
               "San Jose"
               "San Francisco"
               "Seattle"
               "Tijuana"
               "Mexicali"
               "Ensenada"
               "Rosarito"
               "Tecate"
               "Vancouver"
               "Surrey"
               "Okanagan"
               "Victoria"
               "Burnaby"
               "Adamstown"),
              -6
              '("Mezcales"
               "San Vicente"
               "Bucerías"
               "Valle de Banderas"
               "Belize City"
               "San Ignacio"
               "Orange Walk"
               "Belmopan"
               "Dangriga"
               "Chicago"
               "Houston"
               "San Antonio"
               "Dallas"
               "Austin"
               "San José"
               "Limón"
               "San Francisco"
               "Alajuela"
               "Liberia"
               "San Salvador"
               "Soyapango"
               "Santa Ana"
               "San Miguel"
               "Mejicanos"
               "Guatemala City"
               "Mixco"
               "Villa Nueva"
               "Petapa"
               "San Juan Sacatepéquez"
               "Tell City"
               "Managua"
               "León"
               "Masaya"
               "Chinandega"
               "Matagalpa"
               "Reynosa"
               "Heroica Matamoros"
               "Nuevo Laredo"
               "Piedras Negras"
               "Ciudad Acuña"
               "Menominee"
               "Iron Mountain"
               "Kingsford"
               "Ironwood"
               "Iron River"
               "Mérida"
               "Campeche"
               "Ciudad del Carmen"
               "Kanasín"
               "Valladolid"
               "Mexico City"
               "Iztapalapa"
               "Ecatepec de Morelos"
               "Guadalajara"
               "Puebla"
               "Monterrey"
               "Saltillo"
               "Guadalupe"
               "Torreón"
               "Victoria de Durango"
               "Mandan"
               "Saskatoon"
               "Regina"
               "Prince Albert"
               "Moose Jaw"
               "North Battleford"
               "Swift Current"
               "Tegucigalpa"
               "San Pedro Sula"
               "Choloma"
               "La Ceiba"
               "El Progreso"
               "Winnipeg"
               "Brandon"
               "Kenora"
               "Portage la Prairie"
               "Thompson"
               "Puerto Ayora"
               "Puerto Baquerizo Moreno"),
              13
              '("Apia"
               "Asau"
               "Mulifanua"
               "Afega"
               "Leulumoega"
               "Atafu Village"
               "Nukunonu"
               "Fale old settlement"
               "Nuku‘alofa"
               "Lapaha"
               "Neiafu"
               "Pangai"
               "‘Ohonua"),
              -3
              '("Palmas"
               "Araguaína"
               "Gurupi"
               "Miracema do Tocantins"
               "Porto Franco"
               "Buenos Aires"
               "La Plata"
               "Mar del Plata"
               "Morón"
               "Bahía Blanca"
               "San Fernando del Valle de Catamarca"
               "Trelew"
               "Puerto Madryn"
               "Esquel"
               "Rawson"
               "Córdoba"
               "Rosario"
               "Santa Fe"
               "Resistencia"
               "Santiago del Estero"
               "San Salvador de Jujuy"
               "San Pedro de Jujuy"
               "Libertador General San Martín"
               "Palpalá"
               "La Quiaca"
               "La Rioja"
               "Chilecito"
               "Arauco"
               "Chamical"
               "Mendoza"
               "San Rafael"
               "San Martín"
               "Comodoro Rivadavia"
               "Río Gallegos"
               "Caleta Olivia"
               "Pico Truncado"
               "Puerto Deseado"
               "Salta"
               "Neuquén"
               "Santa Rosa"
               "San Carlos de Bariloche"
               "Cipolletti"
               "San Juan"
               "Chimbas"
               "Santa Lucía"
               "Pocito"
               "Caucete"
               "San Luis"
               "Villa Mercedes"
               "La Punta"
               "Merlo"
               "Justo Daract"
               "San Miguel de Tucumán"
               "Yerba Buena"
               "Tafí Viejo"
               "Alderetes"
               "Aguilares"
               "Ushuaia"
               "Río Grande"
               "Salvador"
               "Feira de Santana"
               "Vitória da Conquista"
               "Itabuna"
               "Camaçari"
               "Belém"
               "Ananindeua"
               "Macapá"
               "Parauapebas"
               "Marabá"
               "Cayenne"
               "Matoury"
               "Saint-Laurent-du-Maroni"
               "Kourou"
               "Rémire-Montjoly"
               "Fortaleza"
               "São Luís"
               "Natal"
               "Teresina"
               "João Pessoa"
               "Nuuk"
               "Sisimiut"
               "Ilulissat"
               "Qaqortoq"
               "Aasiaat"
               "Maceió"
               "Aracaju"
               "Arapiraca"
               "Nossa Senhora do Socorro"
               "São Cristóvão"
               "Saint-Pierre"
               "Miquelon"
               "Montevideo"
               "Salto"
               "Paysandú"
               "Las Piedras"
               "Rivera"
               "Paramaribo"
               "Lelydorp"
               "Brokopondo"
               "Nieuw Nickerie"
               "Moengo"
               "Punta Arenas"
               "Puerto Natales"
               "Recife"
               "Jaboatão"
               "Jaboatão dos Guararapes"
               "Olinda"
               "Paulista"
               "Santarém"
               "Altamira"
               "Itaituba"
               "Oriximiná"
               "Alenquer"
               "São Paulo"
               "Rio de Janeiro"
               "Belo Horizonte"
               "Brasília"
               "Curitiba"
               "La Legua-San Jacinto"
               "Stanley"),
              6
              '("Almaty"
               "Karagandy"
               "Shymkent"
               "Taraz"
               "Nur-Sultan"
               "Bishkek"
               "Osh"
               "Jalal-Abad"
               "Karakol"
               "Tokmok"
               "Dhaka"
               "Chittagong"
               "Khulna"
               "Rājshāhi"
               "Comilla"
               "Omsk"
               "Tara"
               "Kalachinsk"
               "Znamenskoye"
               "Tavricheskoye"
               "Kostanay"
               "Rudnyy"
               "Dzhetygara"
               "Arkalyk"
               "Lisakovsk"
               "Thimphu"
               "Punākha"
               "Tsirang"
               "Phuntsholing"
               "Pemagatshel"
               "Zhongshan"
               "Ürümqi"
               "Zhanjiang"
               "Shihezi"
               "Huocheng"),
              3
              '("Addis Ababa"
               "Dire Dawa"
               "Mek'ele"
               "Nazrēt"
               "Bahir Dar"
               "Asmara"
               "Keren"
               "Massawa"
               "Assab"
               "Mendefera"
               "Dar es Salaam"
               "Mwanza"
               "Zanzibar"
               "Arusha"
               "Mbeya"
               "Djibouti"
               "'Ali Sabieh"
               "Tadjourah"
               "Obock"
               "Dikhil"
               "Juba"
               "Winejok"
               "Malakal"
               "Wau"
               "Pajok"
               "Kampala"
               "Gulu"
               "Lira"
               "Mbarara"
               "Jinja"
               "Mogadishu"
               "Hargeysa"
               "Berbera"
               "Kismayo"
               "Marka"
               "Nairobi"
               "Mombasa"
               "Nakuru"
               "Eldoret"
               "Kisumu"
               "Sanaa"
               "Al Ḩudaydah"
               "Ta‘izz"
               "Aden"
               "Mukalla"
               "Baghdad"
               "Basrah"
               "Al Mawşil al Jadīdah"
               "Al Başrah al Qadīmah"
               "Mosul"
               "Manama"
               "Al Muharraq"
               "Ar Rifā‘"
               "Dār Kulayb"
               "Madīnat Ḩamad"
               "Al Aḩmadī"
               "Ḩawallī"
               "As Sālimīyah"
               "Şabāḩ as Sālim"
               "Al Farwānīyah"
               "Doha"
               "Ar Rayyān"
               "Umm Şalāl Muḩammad"
               "Al Wakrah"
               "Al Khawr"
               "Riyadh"
               "Jeddah"
               "Mecca"
               "Medina"
               "Sulţānah"
               "Istanbul"
               "Ankara"
               "İzmir"
               "Bursa"
               "Adana"
               "Kirov"
               "Kirovo-Chepetsk"
               "Vyatskiye Polyany"
               "Slobodskoy"
               "Kotel’nich"
               "Minsk"
               "Homyel'"
               "Mahilyow"
               "Vitebsk"
               "Hrodna"
               "Moscow"
               "Saint Petersburg"
               "Nizhniy Novgorod"
               "Kazan"
               "Rostov-na-Donu"
               "Simferopol"
               "Kerch"
               "Yevpatoriya"
               "Yalta"
               "Feodosiya"
               "Antananarivo"
               "Toamasina"
               "Antsirabe"
               "Fianarantsoa"
               "Mahajanga"
               "Moroni"
               "Moutsamoudou"
               "Fomboni"
               "Domoni"
               "Tsimbeo"
               "Mamoudzou"
               "Koungou"
               "Dzaoudzi"
               "Dembeni"
               "Sada"),
              12
              '("Anadyr"
               "Bilibino"
               "Petropavlovsk-Kamchatsky"
               "Yelizovo"
               "Vilyuchinsk"
               "Klyuchi"
               "Mil’kovo"
               "Auckland"
               "Wellington"
               "Christchurch"
               "Manukau City"
               "North Shore"
               "Suva"
               "Lautoka"
               "Nadi"
               "Labasa"
               "Ba"
               "Funafuti"
               "Savave Village"
               "Tanrake Village"
               "Toga Village"
               "Asau Village"
               "Ebaye"
               "Jabat"
               "Majuro"
               "Arno"
               "Jabor"
               "Wotje"
               "Mili"
               "Yaren"
               "Baiti"
               "Anabar"
               "Uaboe"
               "Ijuw"
               "Tarawa"
               "Betio Village"
               "Bikenibeu Village"
               "Mata-Utu"
               "Leava"
               "Alo"),
              2
              '("Lilongwe"
               "Blantyre"
               "Mzuzu"
               "Zomba"
               "Kasungu"
               "Bujumbura"
               "Muyinga"
               "Gitega"
               "Ruyigi"
               "Ngozi"
               "Cairo"
               "Alexandria"
               "Giza"
               "Port Said"
               "Suez"
               "Gaborone"
               "Francistown"
               "Molepolole"
               "Selebi-Phikwe"
               "Maun"
               "Harare"
               "Bulawayo"
               "Chitungwiza"
               "Mutare"
               "Gweru"
               "Cape Town"
               "Durban"
               "Johannesburg"
               "Soweto"
               "Pretoria"
               "Khartoum"
               "Omdurman"
               "Nyala"
               "Port Sudan"
               "Kassala"
               "Kigali"
               "Butare"
               "Gitarama"
               "Musanze"
               "Gisenyi"
               "Lubumbashi"
               "Mbuji-Mayi"
               "Kisangani"
               "Kananga"
               "Likasi"
               "Lusaka"
               "Kitwe"
               "Ndola"
               "Kabwe"
               "Chingola"
               "Maputo"
               "Matola"
               "Beira"
               "Nampula"
               "Chimoio"
               "Maseru"
               "Mafeteng"
               "Leribe"
               "Maputsoe"
               "Mohale’s Hoek"
               "Manzini"
               "Mbabane"
               "Big Bend"
               "Malkerns"
               "Nhlangano"
               "Tripoli"
               "Benghazi"
               "Mişrātah"
               "Tarhuna"
               "Al Khums"
               "Windhoek"
               "Rundu"
               "Walvis Bay"
               "Oshakati"
               "Swakopmund"
               "Amman"
               "Zarqa"
               "Irbid"
               "Russeifa"
               "Wādī as Sīr"
               "Beirut"
               "Ra’s Bayrūt"
               "Tripoli"
               "Sidon"
               "Tyre"
               "Aleppo"
               "Damascus"
               "Homs"
               "Ḩamāh"
               "Latakia"
               "Famagusta"
               "Kyrenia"
               "Protaras"
               "Paralímni"
               "Rizokárpaso"
               "Gaza"
               "Khān Yūnis"
               "Jabālyā"
               "Rafaḩ"
               "Dayr al Balaḩ"
               "East Jerusalem"
               "Hebron"
               "Nablus"
               "Battir"
               "Ţūlkarm"
               "Jerusalem"
               "Tel Aviv"
               "West Jerusalem"
               "Haifa"
               "Ashdod"
               "Nicosia"
               "Limassol"
               "Larnaca"
               "Stróvolos"
               "Paphos"
               "Athens"
               "Thessaloníki"
               "Pátra"
               "Piraeus"
               "Lárisa"
               "Bucharest"
               "Sector 3"
               "Sector 6"
               "Sector 2"
               "Iaşi"
               "Chisinau"
               "Tiraspol"
               "Bălţi"
               "Bender"
               "Rîbniţa"
               "Helsinki"
               "Espoo"
               "Tampere"
               "Vantaa"
               "Turku"
               "Kaliningrad"
               "Chernyakhovsk"
               "Sovetsk"
               "Baltiysk"
               "Gusev"
               "Kyiv"
               "Kharkiv"
               "Dnipro"
               "Donetsk"
               "Odessa"
               "Mariehamn"
               "Riga"
               "Daugavpils"
               "Liepāja"
               "Jelgava"
               "Jūrmala"
               "Sofia"
               "Plovdiv"
               "Varna"
               "Burgas"
               "Ruse"
               "Tallinn"
               "Tartu"
               "Narva"
               "Kohtla-Järve"
               "Pärnu"
               "Uzhgorod"
               "Mukachevo"
               "Khust"
               "Berehove"
               "Tyachiv"
               "Vilnius"
               "Kaunas"
               "Klaipėda"
               "Šiauliai"
               "Panevėžys"
               "Zaporizhia"
               "Luhansk"
               "Sevastopol"
               "Melitopol"
               "Syevyerodonets’k"),
              -7
              '("Boise"
               "Meridian"
               "Nampa"
               "Idaho Falls"
               "Pocatello"
               "Chihuahua"
               "Ciudad Delicias"
               "Cuauhtémoc"
               "Parral"
               "Nuevo Casas Grandes"
               "Fort St. John"
               "Dawson Creek"
               "Denver"
               "El Paso"
               "Albuquerque"
               "Colorado Springs"
               "Aurora"
               "Calgary"
               "Edmonton"
               "Fort McMurray"
               "Red Deer"
               "Lethbridge"
               "Hermosillo"
               "Ciudad Obregón"
               "Nogales"
               "San Luis Río Colorado"
               "Navojoa"
               "Culiacán"
               "Mazatlán"
               "Tepic"
               "Los Mochis"
               "La Paz"
               "Juárez"
               "Manuel Ojinaga"
               "Ojinaga"
               "Phoenix"
               "Tucson"
               "Mesa"
               "Chandler"
               "Gilbert"
               "Whitehorse"
               "Yellowknife"),
              11
              '("Magadan"
               "Ust-Nera"
               "Susuman"
               "Ola"
               "Yuzhno-Sakhalinsk"
               "Korsakov"
               "Kholmsk"
               "Okha"
               "Nevel’sk"
               "Arawa"
               "Buka"
               "Port-Vila"
               "Luganville"
               "Isangel"
               "Sola"
               "Lakatoro"
               "Honiara"
               "Malango"
               "Auki"
               "Gizo"
               "Buala"
               "Tofol"
               "Kingston"
               "Nouméa"
               "Mont-Dore"
               "Dumbéa"
               "Païta"
               "Wé"
               "Kolonia"
               "Kolonia Town"
               "Palikir - National Government Center"),
              -11 '("Alofi" "Pago Pago" "Tāfuna" "Ta`ū" "Taulaga"),
              9
              '("Chita"
               "Krasnokamensk"
               "Borzya"
               "Petrovsk-Zabaykal’skiy"
               "Aginskoye"
               "Dili"
               "Maliana"
               "Suai"
               "Likisá"
               "Aileu"
               "Ambon"
               "Jayapura"
               "Sorong"
               "Ternate"
               "Abepura"
               "Pyongyang"
               "Hamhŭng"
               "Namp’o"
               "Sunch’ŏn"
               "Hŭngnam"
               "Seoul"
               "Busan"
               "Incheon"
               "Daegu"
               "Daejeon"
               "Tokyo"
               "Yokohama"
               "Osaka"
               "Nagoya"
               "Sapporo"
               "Yakutsk"
               "Blagoveshchensk"
               "Belogorsk"
               "Neryungri"
               "Svobodnyy"
               "Koror"
               "Koror Town"
               "Kloulklubed"
               "Ulimang"
               "Mengellang"),
              5
              '("Shevchenko"
               "Zhanaozen"
               "Beyneu"
               "Shetpe"
               "Yeraliyev"
               "Aktobe"
               "Kandyagash"
               "Shalqar"
               "Khromtau"
               "Embi"
               "Ashgabat"
               "Türkmenabat"
               "Daşoguz"
               "Mary"
               "Balkanabat"
               "Atyrau"
               "Qulsary"
               "Shalkar"
               "Balykshi"
               "Maqat"
               "Dushanbe"
               "Khujand"
               "Kŭlob"
               "Bokhtar"
               "Istaravshan"
               "Karachi"
               "Lahore"
               "Faisalabad"
               "Rawalpindi"
               "Multan"
               "Oral"
               "Aqsay"
               "Zhänibek"
               "Tasqala"
               "Zhumysker"
               "Kyzylorda"
               "Baikonur"
               "Novokazalinsk"
               "Aral"
               "Chiili"
               "Samarkand"
               "Bukhara"
               "Nukus"
               "Qarshi"
               "Jizzax"
               "Tashkent"
               "Namangan"
               "Andijon"
               "Qo‘qon"
               "Chirchiq"
               "Yekaterinburg"
               "Chelyabinsk"
               "Ufa"
               "Perm"
               "Orenburg"
               "Port-aux-Français"
               "Male"
               "Fuvahmulah"
               "Hithadhoo"
               "Kulhudhuffushi"
               "Thinadhoo"),
              14 '(),
              -9
              '("Anchorage"
               "Fairbanks"
               "Eagle River"
               "Badger"
               "Knik-Fairview"
               "Juneau"
               "Sitka"
               "Ketchikan"),
              -10
              '("Honolulu"
               "East Honolulu"
               "Pearl City"
               "Hilo"
               "Kailua"
               "Avarua"
               "Faaa"
               "Papeete"
               "Punaauia"
               "Pirae"
               "Mahina"),
              10
              '("Vladivostok"
               "Khabarovsk"
               "Khabarovsk Vtoroy"
               "Komsomolsk-on-Amur"
               "Ussuriysk"
               "Brisbane"
               "Gold Coast"
               "Logan City"
               "Townsville"
               "Cairns"
               "Hobart"
               "Launceston"
               "Burnie"
               "Devonport"
               "Sandy Bay"
               "Melbourne"
               "Geelong"
               "Bendigo"
               "Ballarat"
               "Melbourne City Centre"
               "Sydney"
               "Canberra"
               "Newcastle"
               "Wollongong"
               "Maitland"
               "Weno"
               "Colonia"
               "Dededo Village"
               "Yigo Village"
               "Tamuning"
               "Tamuning-Tumon-Harmon Village"
               "Mangilao Village"
               "Port Moresby"
               "Lae"
               "Mount Hagen"
               "Popondetta"
               "Madang"
               "Saipan"
               "San Jose Village"),
              -5
              '("Bogotá"
               "Cali"
               "Medellín"
               "Barranquilla"
               "Cartagena"
               "Cancún"
               "Chetumal"
               "Playa del Carmen"
               "Cozumel"
               "Felipe Carrillo Puerto"
               "George Town"
               "West Bay"
               "Bodden Town"
               "East End"
               "North Side"
               "Detroit"
               "Grand Rapids"
               "Warren"
               "Sterling Heights"
               "Ann Arbor"
               "Eirunepé"
               "Benjamin Constant"
               "Envira"
               "Cockburn Town"
               "Guayaquil"
               "Quito"
               "Cuenca"
               "Santo Domingo de los Colorados"
               "Machala"
               "Havana"
               "Santiago de Cuba"
               "Camagüey"
               "Holguín"
               "Guantánamo"
               "Indianapolis"
               "Fort Wayne"
               "South Bend"
               "Carmel"
               "Bloomington"
               "Vincennes"
               "Jasper"
               "Washington"
               "Huntingburg"
               "Iqaluit"
               "Kingston"
               "New Kingston"
               "Spanish Town"
               "Portmore"
               "Montego Bay"
               "Louisville"
               "Jeffersonville"
               "New Albany"
               "Jeffersontown"
               "Pleasure Ridge Park"
               "Monticello"
               "Lima"
               "Arequipa"
               "Callao"
               "Trujillo"
               "Chiclayo"
               "Nassau"
               "Lucaya"
               "Freeport"
               "West End"
               "Cooper’s Town"
               "New York City"
               "Brooklyn"
               "Queens"
               "Philadelphia"
               "Manhattan"
               "Panamá"
               "San Miguelito"
               "Juan Díaz"
               "David"
               "Arraiján"
               "Port-au-Prince"
               "Carrefour"
               "Delmas 73"
               "Pétionville"
               "Port-de-Paix"
               "Rio Branco"
               "Cruzeiro do Sul"
               "Sena Madureira"
               "Tarauacá"
               "Feijó"
               "Thunder Bay"
               "Toronto"
               "Montréal"
               "Ottawa"
               "Mississauga"
               "Québec"),
              8
              '("Bandar Seri Begawan"
               "Kuala Belait"
               "Seria"
               "Tutong"
               "Bangar"
               "Baruun-Urt"
               "Choibalsan"
               "Hong Kong"
               "Kowloon"
               "Tsuen Wan"
               "Yuen Long Kau Hui"
               "Tung Chung"
               "Irkutsk"
               "Ulan-Ude"
               "Bratsk"
               "Angarsk"
               "Ust’-Ilimsk"
               "Kota Bharu"
               "Kuala Lumpur"
               "Klang"
               "Kampung Baru Subang"
               "Johor Bahru"
               "Kuching"
               "Kota Kinabalu"
               "Sandakan"
               "Tawau"
               "Miri"
               "Macau"
               "Makassar"
               "Denpasar"
               "City of Balikpapan"
               "Banjarmasin"
               "Manado"
               "Quezon City"
               "Manila"
               "Caloocan City"
               "Budta"
               "Davao"
               "Shanghai"
               "Beijing"
               "Tianjin"
               "Guangzhou"
               "Shenzhen"
               "Singapore"
               "Woodlands"
               "Taipei"
               "Kaohsiung"
               "Taichung"
               "Tainan"
               "Banqiao"
               "Ulan Bator"
               "Erdenet"
               "Darhan"
               "Hovd"
               "Murun-kuren"
               "Perth"
               "Rockingham"
               "Mandurah"
               "Bunbury"
               "Albany")})
