(ns website.zones
  (:require [website.zones.data :as data]))

(def fave-places
  '("London"
    "Dublin"
    "Lisbon"
    "Abidjan"
    "Accra"
    "Dakar"
    "Baker Island"
    "Howland Island"
    "Santiago"
    "Santo Domingo"
    "Manaus"
    "Caracas"
    "La Paz"
    "Halifax"
    "Jakarta"
    "Ho Chi Minh City"
    "Bangkok"
    "Krasnoyarsk"
    "Paris"
    "Berlin"
    "Rome"
    "Madrid"
    "Warsaw"
    "Lagos"
    "Kinshasa"
    "Algiers"
    "Casablanca"
    "South Sandwich Islands"
    "Dubai"
    "Baku"
    "Tbilisi"
    "Yerevan"
    "Samara"
    "Greenland"
    "Azores Islands"
    "San Francisco"
    "Los Angeles"
    "Vancouver"
    "Tijuana"
    "Mexico City"
    "Chicago"
    "Guatemala City"
    "Winnipeg"
    "Tegucigalpa"
    "San Jose"
    "San Salvador"
    "Tokelau"
    "Apia"
    "Tonga"
    "São Paulo"
    "Buenos Aires"
    "Montevideo"
    "Dhaka"
    "Almaty"
    "Omsk"
    "Moscow"
    "Istanbul"
    "Riyadh"
    "Baghdad"
    "Addis"
    "Ababa"
    "Doha"
    "Auckland"
    "Suva"
    "Petropavlovsk-Kamchatsky"
    "Cairo"
    "Johannesburg"
    "Khartoum"
    "Kiev"
    "Bucharest"
    "Athens"
    "Jerusalem"
    "Sofia"
    "Phoenix"
    "Calgary"
    "Juárez"
    "New Caledonia"
    "Solomon Islands"
    "American Samoa"
    "Niue"
    "Tokyo"
    "Seoul"
    "Pyongyang"
    "Ambon"
    "Yakutsk"
    "Karachi"
    "Tashkent"
    "Yekaterinburg"
    "Line Islands"
    "Anchorage"
    "Honolulu"
    "Sydney"
    "Port Moresby"
    "Vladicostok"
    "Miami"
    "New York"
    "Toronto"
    "Havana"
    "Lima"
    "Bogotá"
    "Kingston"
    "Shanghai"
    "Taipei"
    "Kuala Lampur"
    "Singapore"
    "Perth"
    "Manila"
    "Makassar"
    "Irkutsk"))

(def offset-cities data/scraped)
